name: scraper_env
channels:
  - conda-forge
dependencies:
  # - python==3.9
  # - pip
  # - eccodes
  - pip:
      # Constraints for Airflow 2.6.2, when running with python 3.9
      # - -c "https://raw.githubusercontent.com/apache/airflow/constraints-2.6.2/constraints-3.9.txt"
      # - poetry
      # - psycopg2-binary
      - apache-airflow
      - pandas
variables:
  PYTHONPATH: /opt/dev/
  AIRFLOW_HOME: /opt/dev/airflow/ 